### ISSUE TITLE
NextCloud recipes

### ISSUE THREAD

**Issue by grahampugh** [eth-its/autopkg-mac-recipes-yaml#12]
New request.

**Comment by katidzehnder** [comment]
needs different regex to compare installed version.

(Testing) '3.3.1.6887' reports '3.3.1git (build 6887)' in inventory

**Comment by grahampugh** [comment]
Thanks. Looks like it needs the CFBundleVersion instead of the CFBundleShortVersionString.

**Comment by grahampugh** [comment]
@katidzehnder I've altered the recipe to use CFBundleVersion; I think it's working now.

**Comment by katidzehnder** [comment]
working now
