### ISSUE TITLE
New Recipe: Thunderbird

### ISSUE THREAD

**Issue by katidzehnder** [eth-its/autopkg-mac-recipes-yaml#20]
only slightly different so might skip

**Comment by grahampugh** [comment]
Reminder: Thunderbird has two recipes for DE/EN.
The version jump up to 91 might indicate some significant code change though (now aligned with Firefox versioning), so it is worth checking if something has changed.

**Comment by katidzehnder** [comment]
the language can indeed be changed in the preferences like it can be done in firefox. tested for thunderbird version 91.0.2

**Comment by katidzehnder** [comment]
new icon in Self_Service_Icons

**Comment by katidzehnder** [comment]
upgrade from version 91.0 (EN installed, DE added in preferences) to 91.0.2 (EN) does keep the added language DE. so this only needs one package.

**Comment by grahampugh** [comment]
Recipes uploaded (not tested)

**Comment by grahampugh** [comment]
@katidzehnder I think this is now done.
