### ISSUE TITLE
TeXShop Uninstaller not working

### ISSUE THREAD

**Issue by katidzehnder** [eth-its/autopkg-mac-recipes-yaml#38]
Uninstaller needs modification due to application beeing stored in /Applications/TeX/TeXShop.app

**Comment by grahampugh** [comment]
@katizehn I think this is now fixed.

**Comment by katidzehnder** [comment]
/Applications/TeX/ is left behind. Application is deleted.

**Comment by grahampugh** [comment]
@katidzehnder I have updated the script to check for an empty `/Applications/TeX` folder (after deleting the `.DS_Store` folder), it works better for me now.

**Comment by katidzehnder** [comment]
Now it is fine. I did test uninstallation with both MacTeX and TexShop. Uninstaller does remove /Applications/TeX now if it is empty after uninstallation but leaves it, if there is still applications present.
